export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_FULFILLED = 'GET_ARTICLES_FULFILLED';
export const GET_ARTICLES_PENDING = 'GET_ARTICLES_PENDING';
export const GET_ARTICLES_REJECTED = 'GET_ARTICLES_REJECTED';

export const GET_ARTICLES_REVIEW = 'GET_ARTICLES_REVIEW';
export const GET_ARTICLES_REVIEW_FULFILLED = 'GET_ARTICLES_REVIEW_FULFILLED';
export const GET_ARTICLES_REVIEW_PENDING = 'GET_ARTICLES_REVIEW_PENDING';
export const GET_ARTICLES_REVIEW_REJECTED = 'GET_ARTICLES_REVIEW_REJECTED';

export const GET_ARTICLES_FEEDBACK = 'GET_ARTICLES_FEEDBACK';
export const GET_ARTICLES_FEEDBACK_FULFILLED =
  'GET_ARTICLES_FEEDBACK_FULFILLED';
export const GET_ARTICLES_FEEDBACK_PENDING = 'GET_ARTICLES_FEEDBACK_PENDING';
export const GET_ARTICLES_FEEDBACK_REJECTED = 'GET_ARTICLES_FEEDBACK_REJECTED';

export const POST_ARTICLES_FEEDBACK = 'POST_ARTICLES_FEEDBACK';
export const POST_ARTICLES_FEEDBACK_FULFILLED =
  'POST_ARTICLES_FEEDBACK_FULFILLED';
export const POST_ARTICLES_FEEDBACK_PENDING = 'POST_ARTICLES_FEEDBACK_PENDING';
export const POST_ARTICLES_FEEDBACK_REJECTED =
  'POST_ARTICLES_FEEDBACK_REJECTED';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_FULFILLED = 'POST_LOGIN_FULFILLED';
export const POST_LOGIN_PENDING = 'POST_LOGIN_PENDING';
export const POST_LOGIN_REJECTED = 'POST_LOGIN_REJECTED';

export const POST_REGISTER = 'POST_REGISTER';
export const POST_REGISTER_FULFILLED = 'POST_REGISTER_FULFILLED';
export const POST_REGISTER_PENDING = 'POST_REGISTER_PENDING';
export const POST_REGISTER_REJECTED = 'POST_REGISTER_REJECTED';

export const PUT_PROFILE = 'PUT_PROFILE';
export const PUT_PROFILE_FULFILLED = 'PUT_PROFILE_FULFILLED';
export const PUT_PROFILE_PENDING = 'PUT_PROFILE_PENDING';
export const PUT_PROFILE_REJECTED = 'PUT_PROFILE_REJECTED';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED';
export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING';
export const GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED';

export const GET_CATAGORIES = 'GET_CATAGORIES';
export const GET_CATAGORIES_FULFILLED = 'GET_CATAGORIES_FULFILLED';
export const GET_CATAGORIES_PENDING = 'GET_CATAGORIES_PENDING';
export const GET_CATAGORIES_REJECTED = 'GET_CATAGORIES_REJECTED';

export const GET_CATAGORIES_ARTICLES = 'GET_CATAGORIES_ARTICLES';
export const GET_CATAGORIES_ARTICLES_FULFILLED =
  'GET_CATAGORIES_ARTICLES_FULFILLED';
export const GET_CATAGORIES_ARTICLES_PENDING =
  'GET_CATAGORIES_ARTICLES_PENDING';
export const GET_CATAGORIES_ARTICLES_REJECTED =
  'GET_CATAGORIES_ARTICLES_REJECTED';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_FULFILLED = 'GET_TAGS_FULFILLED';
export const GET_TAGS_PENDING = 'GET_TAGS_PENDING';
export const GET_TAGS_REJECTED = 'GET_TAGS_REJECTED';

export const GET_TAGS_ARTICLES = 'GET_TAGS_ARTICLES';
export const GET_TAGS_ARTICLES_FULFILLED = 'GET_TAGS_ARTICLES_FULFILLED';
export const GET_TAGS_ARTICLES_PENDING = 'GET_TAGS_ARTICLES_PENDING';
export const GET_TAGS_ARTICLES_REJECTED = 'GET_TAGS_ARTICLES_REJECTED';

export const GET_HEADLINE = 'GET_HEADLINE';
export const GET_HEADLINE_FULFILLED = 'GET_HEADLINE_FULFILLED';
export const GET_HEADLINE_PENDING = 'GET_HEADLINE_PENDING';
export const GET_HEADLINE_REJECTED = 'GET_HEADLINE_REJECTED';

export const GET_SPECIAL_REPORT = 'GET_SPECIAL_REPORT';
export const GET_SPECIAL_REPORT_FULFILLED = 'GET_SPECIAL_REPORT_FULFILLED';
export const GET_SPECIAL_REPORT_PENDING = 'GET_SPECIAL_REPORT_PENDING';
export const GET_SPECIAL_REPORT_REJECTED = 'GET_SPECIAL_REPORT_REJECTED';

export const GET_GAME_OF_THE_WEEK = 'GET_GAME_OF_THE_WEEK';
export const GET_GAME_OF_THE_WEEK_FULFILLED = 'GET_GAME_OF_THE_WEEK_FULFILLED';
export const GET_GAME_OF_THE_WEEK_PENDING = 'GET_GAME_OF_THE_WEEK_PENDING';
export const GET_GAME_OF_THE_WEEK_REJECTED = 'GET_GAME_OF_THE_WEEK_REJECTED';

export const RESET_LOGIN = 'RESET_LOGIN';
