const GET_CURRENCIES = 'GET_CURRENCIES';
const GET_CURRENCIES_FULFILLED = 'GET_CURRENCIES_FULFILLED';
const GET_CURRENCIES_PENDING = 'GET_CURRENCIES_PENDING';
const GET_CURRENCIES_REJECTED = 'GET_CURRENCIES_REJECTED';

export {
  GET_CURRENCIES,
  GET_CURRENCIES_FULFILLED,
  GET_CURRENCIES_PENDING,
  GET_CURRENCIES_REJECTED,
};
